version: "3"
services:
  app:
    build: .
    ports:
      - "5000:3000"
    command: yarn dev
    depends_on:
      - db
    environment:
      - POSTGRES_DB=theredoces
  db:
    image: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=theredoces
volumes:
  postgres-data:

